
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Values.global.name }}
  namespace: {{ .Values.global.clusterNamespace }}
spec:
  schedule: "*/15 * * * *"
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      name: {{ .Values.global.name }}
      namespace: {{ .Values.global.clusterNamespace }}
    spec:
      template:
        metadata:
           namespace: {{ .Values.global.clusterNamespace }}
           labels:
              job: {{ .Values.global.name }}
        spec:
           restartPolicy: OnFailure
           imagePullSecrets:
            - name: {{ .Values.global.imagePullSecrets }}
           containers:
           - name: {{ .Values.global.name }}
             image: us.icr.io/{{ .Values.global.registryNamespace }}/{{ .Values.global.imageName }}:{{ .Values.global.tag | default "dummy" }}
             command:
               - "/bin/sh"
               - "-c"
               - "nohup /kubehunter-sa-adapter/$CLOUD_ENV/updateKubeHunterCard_entryPt.sh $ACCOUNT_ID $API_KEY $CLUSTER_NAME $OC_LOGIN_APIKEY"
             volumeMounts:
             - name: kubectl-binary
               mountPath: /usr/bin/kubectl
               readOnly: true
             - name: kubectl-config
               mountPath: /etc/kubernetes/config
               readOnly: true             
## Define Env variables
             env:
             - name: ACCOUNT_ID
               valueFrom:
                 secretKeyRef:
                   name: kubehunter-redhat-credentials
                   key: account_id
             - name: API_KEY
               valueFrom:
                 secretKeyRef:
                   name: kubehunter-redhat-credentials
                   key: api_key    
             - name: CLUSTER_NAME
               valueFrom:
                 secretKeyRef:
                   name: kubehunter-redhat-credentials
                   key: cluster_name 
             - name: OC_LOGIN_APIKEY
               valueFrom:
                 secretKeyRef:
                   name: kubehunter-redhat-credentials
                   key: oc_login_apikey   
             - name: SA_ENDPOINT
               valueFrom:
                 configMapKeyRef:
                   name: kubehunter-sa-adapter-redhat-configuration
                   key: saEndpoint
             - name: TOKEN_URL
               valueFrom:
                 configMapKeyRef:
                   name: kubehunter-sa-adapter-redhat-configuration
                   key: tokenUrl
             - name: CLOUD_ENV
               valueFrom:
                 configMapKeyRef:
                   name: kubehunter-sa-adapter-redhat-configuration
                   key: cloudEnv  
             - name: REGION
               valueFrom:
                 configMapKeyRef:
                   name: kubehunter-sa-adapter-redhat-configuration
                   key: region
             - name: LOGIN_ENDPOINT
               valueFrom:
                 configMapKeyRef:
                   name: kubehunter-sa-adapter-redhat-configuration
                   key: loginEndpoint                                                       
           volumes:
             - name: kubectl-binary
               hostPath:
                  path: /usr/bin/kubectl
             - name: kubectl-config
               hostPath:
                 path: /etc/kubernetes/config